---
- name: install dynatrace agent
  hosts: all
  roles:
    - role: dynatrace-agent
      install_with: chocolatey  # or 'package' for ad-hoc installation
      state: present # or 'absent' to remove