- name: SQL 2016/2019 Create DB tables with DSC
  hosts: all
  vars:
    login_user: sa
    login_password: "{{ mssql_password }}"
    instance_name: "{{ ansible_hostname }}"

  roles:
  - sql_run_sql_script_dsc