- name: Create a db on MSSQL
  hosts: all
  gather_facts: no
  become: no
  vars:
    db_name: rhdemo1

  tasks:
    - name: Set windows connection variables
      set_fact:
        ansible_port: 5986
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
      delegate_to: 127.0.0.1

    - name: Enable port for MSSQL
      win_firewall_rule:
        name: MSSQL
        localport: 1433
        action: allow
        direction: in
        protocol: tcp
        profiles: public
        state: present
        enabled: yes

    - name: Create a db
      mssql_db:
        login_host: "{{ ansible_host | default(ansible_ssh_host) | default(inventory_hostname) }}"
        login_user: sa
        login_password: '{{ mssql_password }}'
        name: '{{ db_name }}'
        state: present
      delegate_to: 127.0.0.1