- name: install Windows Updates
  hosts: all

  tasks:
    - block:

        - name: check for missing updates.
          win_updates:
            state: searched
          register: update_count

        - debug:
            var: update_count

        - name: install all windows updates
          win_updates:
            category_names:
              - CriticalUpdates
              - DefinitionUpdates
              - SecurityUpdates
              - UpdateRollups
              - Updates
            reboot: yes
          when: update_count.found_update_count|int >= 1

      rescue:

        - name: reboot before continue to retry
          win_reboot:

        - name: install all windows updates (retry)
          win_updates:
            category_names:
            - CriticalUpdates
            - DefinitionUpdates
            - SecurityUpdates
            - UpdateRollups
            - Updates
            reboot: yes

      always:

        - name: check for missing updates.
          win_updates:
            state: searched
          register: update_count

        - name: list missing updates
          debug:
            var: update_count