- name: Whoami
  hosts: all

  tasks:
    - name: find whoami based on credentials supplied
      win_whoami:
      register: whoami_base

    - name: output base user
      debug:
        msg: "{{ whoami_base.account.account_name }}"