- hosts: localhost
  become: no
  tasks:
    - name: get ec2 instance information
      ec2_instance_facts:
        region: "{{ ec2_region }}"
        filters:
          vpc-id: "{{ ec2_vpc_id }}"
          "tag:app": windows_demo
      register: ec2_instances

    - name: terminate instances
      ec2:
        region: "{{ ec2_region }}"
        state: "absent"
        instance_ids: "{{ ec2_instances.instances | map(attribute='instance_id') | list }}"

    - name: Get record for router ELB DNS Entry
      route53:
        command: get
        zone: "{{ hosted_zone_domain_name }}"
        record: "{{ subdomain | default(ec2_instances.instances[0].tags.role | lower) }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
        type: A
      register: routerelbrec
      when: hosted_zone_domain_name is defined and ec2_name_prefix is defined

    - name: Delete Router ELB DNS Entry if it doesn't exist
      route53:
        #state: present ## Added in Ansible 2.4 will remove need for when statement below
        command: delete
        zone: "{{ hosted_zone_domain_name }}"
        record: "{{ subdomain | default(ec2_instances.instances[0].tags.role | lower) }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
        type: A
        value: "{{ ec2_instances.instances[0].public_ip_address }}"
      when: routerelbrec.set is defined and "{} != routerelbrec.set"