- name: Deploy Windows Instance on Azure
  hosts: localhost
  gather_facts: False
  connection: local
  become: no
  vars:
    ansible_port: 5986
    windows: yes
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: myResourceGroup
        location: southcentralus
        tags:
          testing: testing
          delete: never
      ignore_errors: yes

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: myResourceGroup
        name: myVnet
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: myResourceGroup
        name: mySubnet
        address_prefix: "10.0.1.0/24"
        virtual_network: myVnet

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: myResourceGroup
        allocation_method: Static
        name: myPublicIP

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: myResourceGroup
        name: myNetworkSecurityGroup
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: Create virtual network inteface card
      azure_rm_networkinterface:
        resource_group: myResourceGroup
        name: myNIC
        virtual_network: myVnet
        subnet: mySubnet
        public_ip_name: myPublicIP
        security_group: myNetworkSecurityGroup

    - name: Create Windows VM
      azure_rm_virtualmachine:
        resource_group: myResourceGroup
        name: AnsibleWin2
        vm_size: Standard_A1
        public_ip_allocation_method: Dynamic
        open_ports:
          - 3389
        os_type: Windows
        admin_username: ansible
        admin_password: "{{ ansible_password }}"
        image:
          sku: 2012-R2-Datacenter
          publisher: MicrosoftWindowsServer
          version: latest
          offer: WindowsServer