- name: Windows AD Controller
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    install_with: ini
  roles:
    - role: windows-hostname
      hostname: windc11
    - windows-ad-controller