---

- name: create credential
  win_credential:
    name: smbhost
    type: generic_password
    username: "{{ smb_share_username }}"
    secret: "{{ smb_share_password }}"
    state: present
  vars: &become_vars
    ansible_become: True
    ansible_become_method: runas
    # when using Tower/AWX, you can define become user and password in the Machine credential
    # and comment out ansible_become_user and ansible_become_pass below
    ansible_become_user: '{{ ansible_user }}'
    ansible_become_pass: '{{ ansible_password }}'

- name: ensure CredentialsManager module is available
  win_psmodule:
    name: CredentialManager
    state: present

# you need to use become to access the credentials
- name: access credential store
  win_shell: |
    $cred = Get-StoredCredential -Target smbhost
    $cred.Username | ConvertTo-Json
  register: find_smb_username
  vars: *become_vars

- name: show result
  debug:
    msg: "{{ find_smb_username.stdout | from_json }}"