---
- name: use powershell when on ansible 2.9 or lower
  set_fact:
    run_sql_script_method: powershell
  when: ansible_version.full is version('2.10', '<')

- include_tasks: '{{ run_sql_script_method }}.yml'