---
- name: Create a resource group
  azure.azcollection.azure_rm_resourcegroup:
    name: myResourceGroup
    location: southcentralus
    tags:
      testing: testing
      delete: never
  ignore_errors: yes

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: myResourceGroup
    name: myVnet
    address_prefixes: "10.0.0.0/16"

- name: Add subnet
  azure_rm_subnet:
    resource_group: myResourceGroup
    name: mySubnet
    address_prefix: "10.0.1.0/24"
    virtual_network: myVnet

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: myResourceGroup
    allocation_method: Static
    name: myPublicIP

- name: Create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: myResourceGroup
    name: myNetworkSecurityGroup
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: WINRM
        protocol: Tcp
        destination_port_range: 5986
        access: Allow
        priority: 1002
        direction: Inbound
      - name: RDP
        protocol: Tcp
        destination_port_range: 3389
        access: Allow
        priority: 1003
        direction: Inbound
      - name: MSSQL
        protocol: Tcp
        destination_port_range: 1433
        access: Allow
        priority: 1004
        direction: Inbound
      - name: HTTP
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 1005
        direction: Inbound
      - name: HTTPS
        protocol: Tcp
        destination_port_range: 443
        access: Allow
        priority: 1006
        direction: Inbound

- name: Create virtual network inteface card
  azure_rm_networkinterface:
    resource_group: myResourceGroup
    name: myNIC
    virtual_network: myVnet
    subnet: mySubnet
    ip_configurations:
      - name: ipconfig1
        public_ip_address_name: myPublicIP
        primary: True
    security_group: myNetworkSecurityGroup

- name: Create Windows VM
  azure_rm_virtualmachine:
    resource_group: myResourceGroup
    name: "{{ item.name }}"
    vm_size: "{{ item.vm_size }}"
    public_ip_allocation_method: Dynamic
    managed_disk_type: Standard_LRS
    open_ports:
      - 3389
      - 1433
      - "{{ item.ansible_port | default(ansible_port) | default('5986') }}"
    os_type: "{{ item.os_type | default('Windows') }}"
    network_interfaces: myNIC
    admin_username: ansible
    admin_password: "{{ item.root_password | default(ansible_password) }}"
    image: "{{ item.image }}"
    remove_on_absent: all
    tags:
      role: "{{ item.role }}"
      app_name: "{{ item.app_name }}"
  async: 7200
  poll: 0
  register: deploy
  loop: "{{ nodes }}"
  when: nodes is defined

- name: Wait for instance creation to complete
  async_status: jid="{{ item.ansible_job_id }}"
  register: instances
  until: instances.finished
  retries: 300
  delay: 10
  with_items: "{{ deploy.results }}"

- name: Create VM Extension
  azure_rm_virtualmachine_extension:
    name: "myvmextension-{{ item.0 }}"
    resource_group: myResourceGroup
    virtual_machine_name: "{{ item.1.ansible_facts.azure_vm.name }}"
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: 1.9
    settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible-documentation/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell.exe -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP"}'
    auto_upgrade_minor_version: true
  with_indexed_items: "{{ instances.results }}"
  when: (instances | changed) and (nodes is defined)

- name: Waiting for server to come online
  wait_for:
    host: "{{ item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    port: "{{ ansible_port }}"
    timeout: 600
  loop: "{{ instances.results }}"
  when: (instances | changed) and (nodes is defined)







